### PR TITLE
feat(formula): align to template formula; basic ci support

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

This PR aligns to template-formula. 

Travis tests are undefined because we cannot use oracle URL to download from due to oracle login issue. Need some solution for this issue.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Trace on MacOS
```
----------
          ID: sqlplus-package-archive-install-prepare
    Function: pkg.installed
        Name: curl
      Result: True
     Comment: All specified packages are already installed
     Started: 00:36:20.594619
    Duration: 8760.659 ms
     Changes:   
----------
          ID: sqlplus-package-archive-install-prepare
    Function: pkg.installed
        Name: gzip
      Result: True
     Comment: All specified packages are already installed
     Started: 00:36:29.355542
    Duration: 35.233 ms
     Changes:   
----------
          ID: sqlplus-package-archive-install-prepare
    Function: file.directory
        Name: /usr/local/oracle/12_2
      Result: True
     Comment: Directory /usr/local/oracle/12_2 updated
     Started: 00:36:29.393356
    Duration: 2.78 ms
     Changes:   
              ----------
              /usr/local/oracle/12_2:
                  New Dir
----------
          ID: sqlplus-package-archive-install-basic
    Function: archive.extracted
        Name: /usr/local/oracle/12_2
      Result: True
     Comment: http://example.com/instantclient-basic-macos.x64-12.2.0.1.0.zip extracted to /usr/local/oracle/12_2/, due to absence of one or more files/dirs
     Started: 00:36:29.397156
    Duration: 2046.954 ms
     Changes:   
              ----------
              extracted_files:
                  - instantclient_12_2/BASIC_README
                  - instantclient_12_2/adrci
                  - instantclient_12_2/genezi
                  - instantclient_12_2/libclntsh.dylib
                  - instantclient_12_2/libclntsh.dylib.12.1
                  - instantclient_12_2/libclntshcore.dylib.12.1
                  - instantclient_12_2/libnnz12.dylib
                  - instantclient_12_2/libocci.dylib
                  - instantclient_12_2/libocci.dylib.12.1
                  - instantclient_12_2/libociei.dylib
                  - instantclient_12_2/libocijdbc12.dylib
                  - instantclient_12_2/libons.dylib
                  - instantclient_12_2/liboramysql12.dylib
                  - instantclient_12_2/ojdbc8.jar
                  - instantclient_12_2/uidrvci
                  - instantclient_12_2/xstreams.jar
              updated ownership:
                  True
----------
          ID: sqlplus-package-archive-install-sdk
    Function: archive.extracted
        Name: /usr/local/oracle/12_2
      Result: True
     Comment: http://http://example.com/instantclient-sdk-macos.x64-12.2.0.1.0.zip extracted to /usr/local/oracle/12_2/, due to absence of one or more files/dirs
     Started: 00:36:31.444351
    Duration: 59.29 ms
     Changes:   
              ----------
              extracted_files:
                  - instantclient_12_2/
                  - instantclient_12_2/sdk/
                  - instantclient_12_2/sdk/admin/
                  - instantclient_12_2/sdk/admin/oraaccess.xsd
                  - instantclient_12_2/sdk/demo/
                  - instantclient_12_2/sdk/demo/cdemo81.c
                  - instantclient_12_2/sdk/demo/demo.mk
                  - instantclient_12_2/sdk/demo/occidemo.sql
                  - instantclient_12_2/sdk/demo/occidemod.sql
                  - instantclient_12_2/sdk/demo/occidml.cpp
                  - instantclient_12_2/sdk/demo/occiobj.cpp
                  - instantclient_12_2/sdk/demo/occiobj.typ
                  - instantclient_12_2/sdk/demo/oraaccess.xml
                  - instantclient_12_2/sdk/demo/setuporamysql.sh
                  - instantclient_12_2/sdk/include/
                  - instantclient_12_2/sdk/include/ldap.h
                  - instantclient_12_2/sdk/include/nzerror.h
                  - instantclient_12_2/sdk/include/nzt.h
                  - instantclient_12_2/sdk/include/occi.h
                  - instantclient_12_2/sdk/include/occiAQ.h
                  - instantclient_12_2/sdk/include/occiCommon.h
                  - instantclient_12_2/sdk/include/occiControl.h
                  - instantclient_12_2/sdk/include/occiData.h
                  - instantclient_12_2/sdk/include/occiObjects.h
                  - instantclient_12_2/sdk/include/oci.h
                  - instantclient_12_2/sdk/include/oci1.h
                  - instantclient_12_2/sdk/include/oci8dp.h
                  - instantclient_12_2/sdk/include/ociap.h
                  - instantclient_12_2/sdk/include/ociapr.h
                  - instantclient_12_2/sdk/include/ocidef.h
                  - instantclient_12_2/sdk/include/ocidem.h
                  - instantclient_12_2/sdk/include/ocidfn.h
                  - instantclient_12_2/sdk/include/ociextp.h
                  - instantclient_12_2/sdk/include/ocikpr.h
                  - instantclient_12_2/sdk/include/ocixmldb.h
                  - instantclient_12_2/sdk/include/ocixstream.h
                  - instantclient_12_2/sdk/include/odci.h
                  - instantclient_12_2/sdk/include/oratypes.h
                  - instantclient_12_2/sdk/include/ori.h
                  - instantclient_12_2/sdk/include/orid.h
                  - instantclient_12_2/sdk/include/orl.h
                  - instantclient_12_2/sdk/include/oro.h
                  - instantclient_12_2/sdk/include/ort.h
                  - instantclient_12_2/sdk/include/xa.h
                  - instantclient_12_2/sdk/ott
                  - instantclient_12_2/sdk/ottclasses.zip
                  - instantclient_12_2/sdk/SDK_README
              updated ownership:
                  True
----------
          ID: sqlplus-package-archive-install-sqlplus
    Function: archive.extracted
        Name: /usr/local/oracle/12_2
      Result: True
     Comment: http://example.com/instantclient-sqlplus-macos.x64-12.2.0.1.0.zip extracted to /usr/local/oracle/12_2/, due to absence of one or more files/dirs
     Started: 00:36:31.503875
    Duration: 56.179 ms
     Changes:   
              ----------
              extracted_files:
                  - instantclient_12_2/SQLPLUS_README
                  - instantclient_12_2/glogin.sql
                  - instantclient_12_2/libsqlplus.dylib
                  - instantclient_12_2/libsqlplusic.dylib
                  - instantclient_12_2/sqlplus
              updated ownership:
                  True
----------
          ID: sqlplus-archive-install-file-symlink-sqlplus
    Function: file.symlink
        Name: /usr/local/bin/sqlplus
      Result: True
     Comment: Symlink /usr/local/bin/sqlplus is present and owned by root:wheel
     Started: 00:36:31.560191
    Duration: 607.041 ms
     Changes:   
----------
          ID: sqlplus-config-file-managed-tnsnames_file
    Function: cmd.run
        Name: curl -L -o '/etc/tnsnames.ora' 'None'
      Result: True
     Comment: onlyif condition is false
     Started: 00:36:32.167447
    Duration: 510.009 ms
     Changes:   

Summary for local
------------
Succeeded: 8 (changed=4)
Failed:    0
```

**Comment by noelmcloughlin** [comment]
Need some alternative URL for travis downloads.

http://download.oracle.com/otn/linux/instantclient/122010/ requires oracle login = unusable.

**Comment by myii** [comment]
@noelmcloughlin There are conflicts here:

> ### Conflicting files
> `sqlplus/init.sls`
> `sqlplus/linuxenv.sls`

**Comment by noelmcloughlin** [comment]
Fixed now - thanks for reviewing @myii

**Comment by noelmcloughlin** [comment]
Hi @myii is there any community server available where I could store oracle tarballs?  Oracle stores the tarballs behind a login wall. So for travis I would need to retrieve the tarballs and store on some community server - or disable Travis.  

Three formulas are:
- java-formula
- sqlplus-formula
- sqldeveloper-formula

**Comment by myii** [comment]
> Hi @myii is there any community server available where I could store oracle tarballs? Oracle stores the tarballs behind a login wall. So for travis I would need to retrieve the tarballs and store on some community server - or disable Travis.
> 
> Three formulas are:
> 
> * java-formula
> * sqlplus-formula
> * sqldeveloper-formula

@noelmcloughlin We don't have anything at the moment and I'm not sure what the issues will be in doing so.  Does Oracle permit storing the tarballs elsewhere?  In any case, I'm pretty sure I've come across ways around this, which allow for unattended installations.  Perhaps @dafyddj has come across something similar with `salt-winrepo-ng`.

**Comment by noelmcloughlin** [comment]
You can set `-b oraclelicense=accept-securebackup-cookie` but this only works for current release, which changes frequently so formulas cannot anticipate the URL - to be clear, its unworkable.  

Store the tarballs outside the login wall for Travis CI, there should be no licensing issue - just ensuring the tarball can install - Travis destroys the environment after the tests.

**Comment by myii** [comment]
> You can set `-b oraclelicense=accept-securebackup-cookie` but this only works for current release, which changes frequently so formulas cannot anticipate the URL - to be clear, its unworkable.
> 
> Store the tarballs outside the login wall for Travis CI, there should be no licensing issue - just ensuring the tarball can install - Travis destroys the environment after the tests.

@noelmcloughlin And there's no "symlink"-style URL that always points to the latest release?

**Comment by noelmcloughlin** [comment]
No.   Sqlplus, Sqldeveloer, and sun-java never had travis running.

For Java, login is required for all except current release (which changes) accepting `-b oraclelicense=accept-securebackup-cookie` but you need to keep raising PRs to maintain this. 

https://github.com/saltstack-formulas/sun-java-formula/pull/9
https://github.com/saltstack-formulas/sun-java-formula/pull/11
https://github.com/saltstack-formulas/sun-java-formula/pull/12
https://github.com/saltstack-formulas/sun-java-formula/pull/13
https://github.com/saltstack-formulas/sun-java-formula/pull/16
https://github.com/saltstack-formulas/sun-java-formula/pull/17
https://github.com/saltstack-formulas/sun-java-formula/pull/38
https://github.com/saltstack-formulas/sun-java-formula/pull/41
https://github.com/saltstack-formulas/sun-java-formula/pull/51
https://github.com/saltstack-formulas/sun-java-formula/pull/52
https://github.com/saltstack-formulas/sun-java-formula/pull/55
https://github.com/saltstack-formulas/sun-java-formula/pull/58
https://github.com/saltstack-formulas/sun-java-formula/pull/60

**Comment by noelmcloughlin** [comment]
see https://github.com/saltstack-formulas/sun-java-formula/pull/16#issuecomment-177286642

**Comment by myii** [comment]
> No. Sqlplus, Sqldeveloer, and sun-java never had travis running.
> 
> For Java, login is required for all except current release (which changes) accepting `-b oraclelicense=accept-securebackup-cookie` but you need to keep raising PRs to maintain this.

@noelmcloughlin And there's _nowhere_ that this current-release URL isn't already available, that we could grab using `curl` or similar?  Surely someone out there is updating the links, that we can parse for our formulas, rather than providing them inline.

**Comment by noelmcloughlin** [comment]
But just to be clear, the formula user still needs to manage release/checksum pillars.  I'm only concerned with Travis here in this discussion.

**Comment by noelmcloughlin** [comment]
> there's nowhere that this current-release URL isn't already available, 

Typically companies store the tarballs on some internal server. Because they would want their Java developer installing and using a known (recommended) release.   There may be some public servers which have the tarballs but they are unofficial (not oracle).  So I was hoping Saltstack community could provide a mirror for oracle java/sqlplus/sqldevelopere for Travis CI.

**Comment by myii** [comment]
@noelmcloughlin Would this help in any way: https://stackoverflow.com/a/14307459.

* http://javadl-esd-secure.oracle.com/update/baseline.version

**Comment by dafyddj** [comment]
> Perhaps @dafyddj has come across something similar with `salt-winrepo-ng`.

I do store some binaries outside of a login-wall in S3/[B2](https://www.backblaze.com/b2/cloud-storage.html) buckets for private use only, but I haven't done it within a tested formula.

But I have thought about this and if the situation arose I was going to try to provide the external url privately in the CI repository settings.

**Comment by myii** [comment]
> I do store some binaries outside of a login-wall in S3/[B2](https://www.backblaze.com/b2/cloud-storage.html) buckets for private use only, but I haven't done it within a tested formula.
> 
> But I have thought about this and if the situation arose I was going to try to provide the external url privately in the CI repository settings.

Appreciate the response, @dafyddj.  That's definitely a useful way to proceed, if we arrange some storage for this org.  It's a relatively low-impact solution for Travis testing _within_ the org -- I'm not sure what we're going to do about testing in users' Travis forks and local testing, though.

**Comment by dafyddj** [comment]
Yes, that is something that would need to be resolved.

**Comment by noelmcloughlin** [comment]
> Would this help in any way: https://stackoverflow.com/a/14307459.

Interesting. But oracle Java URL includes a hash sum of something (I tried to guess/hack what the hash represents without success). So need unique HASH and VERSION values for OTN downloads.
` HTTP://oracle.com/otn/java/<hashsum>/ora<version><arch><etc>.tar.gz`

Ideally, we have checksums too.  The historical PRs show people have struggled for years with this.

**Comment by noelmcloughlin** [comment]
> But I have thought about this and if the situation arose I was going to try to provide the external url privately in the CI repository settings.

Something like that - for this community Travis CI only - would be great

**Comment by noelmcloughlin** [comment]
Is this okay to merge @myii ?

**Comment by myii** [comment]
@noelmcloughlin Travis is failing for all instances, those need to be resolved first one way or another.

**Comment by myii** [comment]
@noelmcloughlin By "another", I mean simply disabling all of the instances from running except for the lint job.

**Comment by noelmcloughlin** [comment]
Selfie merging - this is the same minor fix for all JetBrains formulae.

**Comment by noelmcloughlin** [comment]
@myii I disabled Travis CI tests for now.

**Comment by myii** [comment]
@noelmcloughlin Merged, with standardising commit added: 5123275.

**Pull request merged**
